---
title: "Check names"
author: "Duncan Golicher"
date: "5/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}
load("/home/rstudio/shiny/primates/primate_ranges.rda")
load("/home/rstudio/shiny/primates/gbif_primates.rda")
load("/home/rstudio/shiny/primates/primates_maps.rda")

# library(tidyr)
# primates_maps %>% separate(NAME,into =c("Genus","Species","Sub")) -> primates_maps 
# primates_maps$binomial<- paste(primates_maps$Genus,primates_maps$Species)

# save(primates_maps,file="/home/rstudio/shiny/primates/primates_maps.rda")

#library(readxl)
#new_list<- read_excel("~/shiny/primates/distribution_maps_3/IUCN_Apr2020_SelectedGeneraCovid.xlsx")$binomial
# save(new_list,file="new_list.rda")


binoms1<-unique(primate_ranges$binomial)
binoms2<-unique(gbif$species)
binoms3<-unique(as.character(primates_maps$binomial))
binoms3
binoms<-binoms1[binoms1%in% binoms2]
binoms<-binoms[binoms%in% binoms3]

binoms<-binoms3[!binoms3%in% binoms1]
#binoms<-binoms[binoms%in% binoms3]

```





```{r}
library(taxize)
d<-synonyms(binoms1, "itis")
iucn_synonyms<-do.call("rbind", d)
save(iucn_synonyms,file="iucn_synonyms.rda")

```



